version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.1-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8080:80'
    depends_on: 
      - db
    restart: unless-stopped
  db: 
    image: postgres:9.6.20
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: varal_aguas
    restart: unless-stopped